### ISSUE TITLE
Drinks and dinner for [Neurotic] before he departs Melbs for San Francisco

### ISSUE THREAD

**Issue by nicholasf** [polyhack/helloworld#13]
@markmandel is relocating to San Francisco and joining Google over there. So let's have some drinks and dinner to celebrate this! 

YEAH!!

![partytime](http://media.giphy.com/media/JBBq4FCnpy3q8/giphy.gif)

When: after work on onwards, Friday evening, 24th April
Where: In a place far far away (in Melbourne CBD somewhere)

We'll probably grab a meal in Chinatown, or something along those lines. If anyone knows of a cool bar we should check out (that can fit a few of us), please list your suggestion here. 

+1 if you are intending to come, so we can have an idea of numbers. I'll seek confirmation in the final week if I need to book anywhere.

**Comment by SomeoneWeird** [comment]
+1

**Comment by markmandel** [comment]
I'll def be there :tada:

**Comment by mipearson** [comment]
:beer: 

also excellent choice of gif

**Comment by DamonOehlman** [comment]
@markmandel congrats, won't be able to make it (Sydney and all) but someone have a beer for me :)

... and yes wonderful gif selection.

**Comment by kvanberendonck** [comment]
Tentative +1.

And grats, Google sounds like an awesome place to work.

**Comment by joshwnj** [comment]
+1

**Comment by aussiegeek** [comment]
I'll be there

**Comment by sporto** [comment]
Will do my best to be there

**Comment by lukebakker000** [comment]
Ahh crap thats my wifes birthday! NOOOO!

Ahh well have fun without me. :)

**Comment by lukebakker000** [comment]
Actually the kids want to take her to some fancy restaurant and Erin wants to go to Melbourne, so I might be able to sort something out. ;)

**Comment by nicholasf** [comment]
Hey guys. 

I'm still intending to going to attend this. The only problem is that I am flying back in from San Francisco at 7 am on the day that this is going to be held. But I'm keen to come along for a drink and wish @markmandel bon voyage.

In light of the fact that I'm exploring life post-channel now, would someone else mind working out the location? @mipearson might be a good candidate.

Cheers all. Good to see you are finding your feet. 

Nick

**Comment by mipearson** [comment]
I un-volunteer. I don't know CBD venues at all :/

**Comment by SomeoneWeird** [comment]
We could go to the meaty place we went at the end of last year that @nicholasf recommended?

**Comment by markmandel** [comment]
You mean: http://fancyhanks.com ?

That could work, we could eat and then sit for a while without too much issue with us being there a while.

There is a certain synchronicity in eating American BBQ before I leave to the US :) 

But I don't know the city very well either, I'm not entirely helpful.

**Comment by nicholasf** [comment]
Done. It’s close to my place and I’m going to be a wreck at that time of day.

**Comment by markmandel** [comment]
Sounds like a plan to me. Let's get RSVPs from everyone attending, and we can book a table.

**Comment by bamse16** [comment]
RSVP

**Comment by pomke** [comment]
+3

**Comment by SomeoneWeird** [comment]
RSVP for @divinegod

**Comment by sporto** [comment]
+1

**Comment by SomeoneWeird** [comment]
We should probably think about booking a table soon too, if I remember tomorrow i'll try ring up.

**Comment by mipearson** [comment]
Have I mentioned "thank you for organising this, Adam", yet?

Thank you for organising this, Adam.

**Comment by markmandel** [comment]
What @mipearson said.

:grin:

**Comment by lukebakker000** [comment]
Hey, my plans have changed and I can make it! Put me down if it's not too late please!

**Comment by lukebakker000** [comment]
RSVP

**Comment by joshwnj** [comment]
gahh forgot to RSVP, so consider this one if i'm not too late :)

**Comment by nicholasf** [comment]
It's my intention to come but there's a chance it may not be realistic. I'll be touching down in Melbourne at about 10 am that morning after flying for 17 or more hours. It's only around the corner from me so I'll make it if I'm able.

**Comment by SomeoneWeird** [comment]
I've got ~10 rsvp's and about 3 maybes, i'll book a table for 15.

**Comment by kvanberendonck** [comment]
Sorry Adam, I have to pull out of this, needed for a dyno run :/

**Comment by SomeoneWeird** [comment]
All good, next one :)

**Comment by SomeoneWeird** [comment]
Hey @nicholasf last time you booked did you just ring up and ask for a table? It says on their website they only offer set menus for booked tables :question:

**Comment by nicholasf** [comment]
I rang them about it, then had a chat when I dropped in later on to confirm it.

**Comment by nicholasf** [comment]
@markmandel apologies mate but I won't be able to make it. We're doing lots of planning right now and I've had to reschedule my flight to Friday night instead of Wednesday. I think I'll be back in San Fran later on so we can talk about catching up in USA.

Guys - hope you have a great time. @SomeoneWeird just talk to the staff and explain what's going on, maybe go in there and pick the table you want for the group ahead of time. 

Cheers,
Nick

**Comment by markmandel** [comment]
@nicholasf no worries mate. I think I'll have a few AU friends I'll end up catching up with in SF :)

**Comment by SomeoneWeird** [comment]
Update: I called them, apparently they don't take casual booking anymore. I've email them on the their website for the 'functions' section just saying we want something outside & informal, hopefully i'll hear back tomorrow.

**Comment by SomeoneWeird** [comment]
Okay so, apparently if we want al le carte menu like last time we can't book a table, which is really annoying.

**Comment by markmandel** [comment]
Short version - we're storming the place. We can't get a booking.

Starting time is at 6:30pm.

If you get there earlier, please grab the largest table you can. If not, hover near the people who have the large table so that they feel uncomfortable, and then leave.

![Party](https://hellawickedzine.files.wordpress.com/2013/07/10.gif)

**Comment by joshwnj** [comment]
arrr very sorry @markmandel but I won't be able to make it after all :| 

Best of luck for the big move! Please also send my regards to Hank and his delicious barbequed animals.

**Comment by mipearson** [comment]
Fuck I love that gif.

**Comment by vacri** [comment]
Apologies here as well, I won't be making it - have a grand one, @markmandel 

Stuck at work messing with a database and reading documentation for a second problem...

- v

**Comment by radar** [comment]
@mipearson and I have arrived and we're sitting outside

**Comment by radar** [comment]
To clarify: out the back of Fancy Hanks is where you'll find us.

**Comment by SomeoneWeird** [comment]
:tada: :tada: :tada: :beers:
