### ISSUE TITLE
code of conduct, etc

### ISSUE THREAD

**Issue by nicholasf** [polyhack/helloworld#16]
Here's what I suggest.

1) We elect three people to handle all polyhack matters for 1 year. Those three people can make decisions for the channel; they can maintain the membership list and the website, they can organise polyhack social events. @wolfeidau and I will op them but won't otherwise act for the channel.

2) People who are on the core list at github get to vote. If they aren't there, no vote. The github core list becomes our membership register.

3) We define a code of conduct so people new to the channel can understand what is required of their social behaviour.

The idea is that we evolve our membership so the most active people in the channel control how it runs. There will be mistakes but we'll work them out as they arrive.

**Comment by radar** [comment]
Can we have a line in the code of conduct that says that owners/ops of the organisation shouldn't delete github comments?

**Comment by davidmason** [comment]
I suggest adding commits to https://github.com/polyhack/helloworld/pull/15 as a workflow for proposing and discussing the details in a way that captures them as we go. I am hopeful that it will eventually be in a form that everyone is happy to have linked on the website.

**Comment by SomeoneWeird** [comment]
@radar and if they do they immediately lose all privileges.

**Comment by SomeoneWeird** [comment]
Going to close this, we can work out what we're doing in one of the existing issues.
