### ISSUE TITLE
Community Guidelines Document

### ISSUE THREAD

**Issue by SomeoneWeird** [polyhack/helloworld#21]
Okay, I've merged the PR from @davidmason for the community guidelines. We've left this long enough, so I'm going to kickstart the effort to get it finished.

A few comments from the PR:

We need to figure out what we mean by "_general consensus_. There are a few ways we can look at this, a consensus can be gained by either achieving a percentage of the votes with a "yay", or we can presume consensus if there are no major "nay"'s. Do we wait for a certain number of people to vote? Active members? What percent of them? How long do we wait?

We also need to define specific guidelines. Currently that section of the document is empty, thus making it effectively useless at the moment.

**Comment by SomeoneWeird** [comment]
Taking some points from another comment [here](https://github.com/polyhack/helloworld/issues/10#issuecomment-58301931), I think we need a section on when and how IRC and Github ops are used.
- There should be at _least_ 2 (3?) people who are active in the community with powers at any time, in case something happens to somebody. (how we define active is another question entirely)
- Powers should never be abused, should never be used to quieten or oppress somebody in the channel because their opinion or behaviour differs from yours. We should have a list of things that ops are allowed to do without consulting the community (adding people to the github org, kicking spammers on irc etc). People who are found to have intentionally abused their power will be stripped of it **immediately**.

**Comment by SomeoneWeird** [comment]
The current list of people with 'power' looks like this:

Github:
- Myself
- rvagg
- eugeneware
- timoxley
- mwotten (blackdog)
- deoxxa
- mipearson (mp__)

IRC:
- Myself
- mp__
- [Neurotic]
- damncabbage

**Comment by SomeoneWeird** [comment]
If a member of the community breaks one of the guidelines, depending on the severity, they may be given a warning. If it's severe, people will be asked to weigh in on whether or not to remove said person from the community.

The way [here](https://github.com/polyhack/helloworld/issues/14#issuecomment-86754605) about how to start a vote I mostly agree with, although we should allow people to start a vote on behalf of another person, and vote semi-anonymously (see my comment [here](https://github.com/polyhack/helloworld/pull/15#discussion_r31419951)).

I'm not sure where to start with the general guidelines, we can probably pull quite a few of them out of a general conference code of conduct [like here](http://confcodeofconduct.com/).

@polyhack/core

**Comment by vacri** [comment]
'general consensus' is a hard thing to define. Perhaps if it's not clear what the community agrees to overall and a vote is called for, require a supermajority of 75% of voters to enact a restriction.

**Comment by SomeoneWeird** [comment]
Well. This failed.

**Comment by michaelneale** [comment]
@SomeoneWeird saddest issue close message ever.

**Comment by DamonOehlman** [comment]
:person_frowning: yeah, I didn't read the message, just saw the close notification.

@SomeoneWeird thanks for trying mate - your efforts are appreciated.
