### ISSUE TITLE
Stickers!

### ISSUE THREAD

**Issue by SomeoneWeird** [polyhack/helloworld#7]
So, with CampJS coming up (again!) - I'm going to look at buying stickers, seeing as we left it too late last time. If anyone has any design skills and wants to try their hand at another logo (also see [here](https://github.com/polyhack/helloworld/issues/3)) - just post it.

**Comment by nicholasf** [comment]
Closing. @SomeoneWeird pwned it. We can create a separate ticket to update the site (we need to get a few more names there and update the interests of the current members).
